# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_field_comment_and_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrate',
            options={'verbose_name': 'Integracion', 'verbose_name_plural': 'Integraciones'},
        ),
    ]
