# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-21 14:28
from __future__ import unicode_literals

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_field_validated_structure_on_responsable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change',
            options={'verbose_name': 'Modificar', 'verbose_name_plural': 'Changes'},
        ),
        migrations.AlterModelOptions(
            name='integrate',
            options={'verbose_name': 'Integrate', 'verbose_name_plural': 'Integrates'},
        ),
        migrations.AlterModelOptions(
            name='integration',
            options={'verbose_name': 'Integration', 'verbose_name_plural': 'Integrations'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='responsable',
            options={'verbose_name': 'Responsable', 'verbose_name_plural': 'responsible'},
        ),
        migrations.AlterField(
            model_name='change',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='change',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='change',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='change',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='change',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='integrate',
            name='integration',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Integration', verbose_name='integration'),
        ),
        migrations.AlterField(
            model_name='integrate',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='projects',
            field=models.ManyToManyField(through='app.Integrate', to='app.Project', verbose_name='projects'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='change',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Change', verbose_name='change'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='change_confirmed',
            field=models.BooleanField(default=False, verbose_name='change_confirmed'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='attachment',
            field=models.FileField(blank=True, default=None, null=True, upload_to=app.models.responsable_attachment_path, verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='validated_structure',
            field=models.BooleanField(default=False, verbose_name='validated_structure'),
        ),
    ]
